routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'hasAdminAccess'] ], function () {
    Route::get('/', [App\Http\Controllers\HomeController::class, 'admin'])->name('admin');

    Route::resource('companies', App\Http\Controllers\CompanyController::class);

    Route::resource('employees', App\Http\Controllers\EmployeeController::class);

    Route::resource('administrators', App\Http\Controllers\AdministratorController::class);
   // Route::get('/administrators', [App\Http\Controllers\HomeController::class, 'ok']);
}); 

Route::group(['middleware' => ['auth'] ], function () {
    Route::get('/company', [App\Http\Controllers\CompanyController::class, 'userCompanyDetails']);

    Route::get('/profile', [App\Http\Controllers\UserController::class, 'index']);

    Route::group(['middleware' => ['hasCompanyAccess'] ], function () {
        Route::resource('company_employees', App\Http\Controllers\CompanyEmployeeController::class);
    
    });

}); 

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Company extends Model
{
    use HasFactory, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'logo',
        'website',
        'created_by',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
    //   'location' => 'array',
    //   'attachments' => 'array',
    ];

    /**
     * belongs To relationship.
     */
    public function createdBy()
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    /**
     *  has Many relationship.
     */
    public function employees()
    {
        return $this->hasMany(Employee::class);
    }
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Repositories\CompanyRepository;
use App\Repositories\UserRepository;
use App\Http\Requests\CreateCompanyRequest;
use App\Http\Requests\UpdateCompanyRequest;
use App\Models\Company;
use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Storage;

class CompanyController extends Controller
{
    /** 
     * CompanyRepository, UserRepository
     * **/
    public function __construct(CompanyRepository $companyRepository, UserRepository $userRepository)
    {
        $this->companyRepository = $companyRepository;
        $this->userRepository = $userRepository;
    }
   /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = $this->companyRepository->getAllCompanies();

        return view('admin.company.index')->with('companies', $companies);
    }

     /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.company.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\CreateCompanyRequest  $request
     */
    public function store(CreateCompanyRequest $request)
    {
        if($request->hasFile('image')){
            $path= Storage::disk('public')->put('logos', $request->file('image'));// Store new logo
            $request->merge(['logo' => $path]);
        }

        $request->merge(['created_by' => auth()->user()->id]);
        $input = $request->all(); 

        $company = $this->companyRepository->store($input);

        $access = Str::random(7);
        $input['password'] = Hash::make($access);
        $input['type'] = User::COMPANY_USER;
        $input['type_id'] = $company->id;

        $this->userRepository->store($input, $access);

        //return redirect('/companies');
        return redirect()->route('companies.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Company $company
     */
    public function show(Company $company)
    {
        return view('admin.company.show')->with('company', $company);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Company $company
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company)
    {
        return view('admin.company.edit')->with('company', $company);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request\UpdateCompanyRequest  $request
     * @param  \App\Models\Company $company
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCompanyRequest $request, Company $company)
    {
        if ($request->hasFile('image')) {

            if ($profile->image) {
                if (Storage::disk('public')->exists($profile->image)) {// Delete the old photo from disk
                    Storage::disk('public')->delete($profile->image);
                }
                $path= Storage::disk('public')->put('logos', $request->file('image'));// Store new photo
                $request->merge(['logo' => $path]);    
            } else {
                $path= Storage::disk('public')->put('logos', $request->file('image'));// Store new photo
                $request->merge(['logo' => $path]);   
            }

        }
        $input = $request->all();
        $this->companyRepository->update($company, $input);

        return redirect()->route('companies.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Company $company
     * @return \Illuminate\Http\Response
     */
    public function destroy(Company $company)
    {
        $this->userRepository->remove(User::EMPLOYEE_USER, $company->id);

        $company->delete();

        return back();
    }

    /**
     * Display user company details.
     *
     */
    public function userCompanyDetails()
    {
        $employee = $this->companyRepository->getCompanyDetails();
        $company = $employee->company;
        $employees = $company->employees()->paginate(10);
        
        return view('company')->with('company', $company)
                 ->with('employees', $employees);
    }

}

resources/views/admin/company/create.blade.php
@extends('admin.layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Create A New Company</div>

                    <div class="card-body">
                        @if($errors->any())
                            <div class="alert alert-danger mb-4">
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </div>
                        @endif

                        <form method="POST" action="{{ route('companies.store') }}" enctype="multipart/form-data">
                            @csrf

                            <div class="text-center mb-4">
                                <div style="width: 30%; margin: 0 auto;">
                                    <img id="file-preview" width="100" height="100" src="{{ asset('images/company.png') }}">
                                    <input id="file" type="file" name="image" class="form-control mt-4" accept="image/*">
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group form-group-default">
                                        <label>Name</label>
                                        <input class="form-control" required name="name" value="{{ old('name') }}">
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group form-group-default">
                                        <label>Email</label>
                                        <input class="form-control" required name="email" value="{{ old('email') }}">
                                    </div>
                                </div>
                
                            </div>

                            <div class="row">
                          
                                <div class="col-md-4">
                                    <div class="form-group form-group-default">
                                        <label>Website</label>
                                        <input class="form-control" name="website" value="{{ old('website') }}">
                                    </div>
                                </div>
                            </div>

                            <div class="text-right mt-4">
                                <button class="btn btn-success">Create</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        function readImage(input) {
            const noImageUrl = "{{ asset('images/company.png') }}";

            if(!input.files) {
                return $('#file-preview').attr('src', noImageUrl);
            }

            if (input.files[0]) {
                const reader = new FileReader();
                
                reader.onload = function(e) {
                    $('#file-preview').attr('src', e.target.result);
                }
                
                reader.readAsDataURL(input.files[0]);
            } else {
                return $('#file-preview').attr('src', noImageUrl);
            }
        }

        $(function() {
            $('#file').change(function() {
                readImage(this);
            });
        });
    </script>
@endsection

resources/views/admin/company/edit.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Companies - Edit ({{ $company->name }})</div>

                    <div class="card-body">
                        @if($errors->any())
                            <div class="alert alert-danger mb-4">
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </div>
                        @endif

                        <form method="POST" action="{{ route('companies.update', $company->id) }}">
                            @csrf
                            @method('PATCH')

                            <div class="text-center mb-4">
                                @if($company->logo)
                                    <img width="100" height="100" src="{{ asset('storage/'. $company->logo) }}">
                                @else
                                    <img width="100" height="100" src="{{ asset('images/no-image-available.png') }}">
                                @endif

                               
                            </div>
                            <!-- <div class="row">
                                <div class="col-md-4">
                                <label>Change Logo</label>
                                <input id="file" type="file" name="image" class="form-control mt-4" accept="image/*">
                                </div>
                            </div> -->

                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group form-group-default">
                                        <label>Name</label>
                                        <input class="form-control" name="name" value="{{ old('name', $company->name) }}">
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group form-group-default">
                                        <label>Email</label>
                                        <input class="form-control" name="email" value="{{ old('email', $company->email) }}">
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group form-group-default">
                                        <label>Website</label>
                                        <input class="form-control" name="website" value="{{ old('website', $company->website) }}">
                                    </div>
                                </div>
                            </div>

                            <div class="text-right mt-4">
                                <button class="btn btn-success">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    
@endsection

resources/views/admin/company/index.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="container">
    <div class="content-header row">
        <div class="content-header-left breadcrumbs-left breadcrumbs-top col-md-6 col-xs-12">
        <div class="breadcrumb-wrapper col-xs-12">
            <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{url('/admin')}}">Home</a>
            </li>
            <li class="breadcrumb-item active">All Companies
            </li>
            </ol>
        </div>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                <div class="text-right mb-4">
                        <a class="btn btn-primary" href="{{ route('companies.create') }}">Create new company</a>
                    </div>
                </div>

                <div class="card-body">
                    <div class="card-block">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">Name</th>
                                        <th scope="col">Email</th>
                                        <th scope="col">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                  @forelse ($companies as $key => $company)
                                    <tr>
                                        <th scope="row">{{$key + 1}}</th>
                                        <td>{{$company->name}}</td>
                                        <td>{{$company->email}}</td>
                                        <td>
                                            <a class="btn btn-sm btn-primary" href="{{ route('companies.show', $company->id) }}">View</a>
                                                <a class="btn btn-sm btn-success" href="{{ route('companies.edit', $company->id) }}">Edit</a>
                                                <form method="POST" action="{{ route('companies.destroy', $company->id) }}" class="d-inline-block">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type='submit' class="btn btn-sm btn-danger">Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                    @empty
                                        <tr>
                                            <td colspan="7" class="text-center"><em>No company added.</em></td>
                                        </tr>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            @isset($companies)
            {{ $companies->links() }}
            @endisset
        </div>
    </div>
</div>
@endsection

resources/views/admin/company/show.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="container">

    <div class="row justify-content-center">
        <div class="col-md-9">
            <div class=" col-md-6">
                <div class="card">
                    <div class="card-body">
                    
                        <div class="card-block">
                        <div class="text-center mb-4">
                            @if($company->logo)
                                <img width="100" height="100" src="{{asset('storage/'. $company->logo)}}">
                            @else
                                <img width="100" height="100" src="{{ asset('images/company.png') }}">
                            @endif
                        </div>
                            <span><strong> Name:</strong> {{$company->name}}</span><br>
                            <span><strong>Email:</strong> {{$company->email}}</span><br>
                            <span><strong>Website:</strong> {{$company->website}}</span><br>
                           @if(auth()->user()->role->role->name == \App\Models\Role::ROLE_SUPER_ADMIN)
                           <span><strong>Created By:</strong> {{$company->createdBy->email}}</span><br>
                           @endif
                           
                            <span><strong>Created At:</strong> {{$company->created_at}}</span><br>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



        



    </div>
@endsection