routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'hasAdminAccess'] ], function () {
    Route::get('/', [App\Http\Controllers\HomeController::class, 'admin'])->name('admin');

    Route::resource('companies', App\Http\Controllers\CompanyController::class);

    Route::resource('employees', App\Http\Controllers\EmployeeController::class);

    Route::resource('administrators', App\Http\Controllers\AdministratorController::class);
   // Route::get('/administrators', [App\Http\Controllers\HomeController::class, 'ok']);
}); 

Route::group(['middleware' => ['auth'] ], function () {
    Route::get('/company', [App\Http\Controllers\CompanyController::class, 'userCompanyDetails']);

    Route::get('/profile', [App\Http\Controllers\UserController::class, 'index']);

    Route::group(['middleware' => ['hasCompanyAccess'] ], function () {
        Route::resource('company_employees', App\Http\Controllers\CompanyEmployeeController::class);
    
    });

}); 

resources/views/admin/manager/index.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="container">
    <div class="content-header row">
        <div class="content-header-left breadcrumbs-left breadcrumbs-top col-md-6 col-xs-12">
        <div class="breadcrumb-wrapper col-xs-12">
            <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{url('/admin')}}">Home</a>
            </li>
            <li class="breadcrumb-item active">All Streets
            </li>
            </ol>
        </div>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-4 ">Dashboard</div>
                        <div class="col-md-6 ">
                    
                        </div>
        
                        <div class="col-md-2">
                            <button class="btn btn-sm btn-primary" type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                                Add New Admin
                            </button>
                        </div>
          
                    </div>
                </div>

                <div class="card-body">
                    <div class="card-block">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">Email</th>
                                        <th scope="col">Role</th>
                                        <th scope="col">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @isset($admins) @foreach ($admins as $key => $admin)
                                    <tr>
                                        <th scope="row">{{$key + 1}}</th>
                                        <td>{{$admin->email}}</td>
                                        <td>{{$admin->role->role->name}}</td>
                                        <td><form method="POST" action="{{ route('administrators.destroy', $admin->id) }}" class="d-inline-block">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type='submit' class="btn btn-sm btn-danger">Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach @endisset
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
       
        </div>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close pull-right" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h5 class="modal-title" id="exampleModalLabel">Add Admin</h5>
            </div>
            <div class="modal-body">
                <div>
                    <form method="POST" action="{{url('/admin/administrators')}}">
                        @csrf
                        <div class="form-group">
                            <label for="details"> Email</label>
                            <input class="form-control" required name="email" value="{{ old('email') }}">
                        </div>
                        <button type="submit" class="btn btn-primary btn-block btn-sm">Add Admin</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


@endsection